### ISSUE TITLE
Managing Users is not idempotent on macOS Big Sur

### ISSUE THREAD

**Issue by ghachey** [weareinteractive/ansible-vsftpd#19]
Not sure if this is because I am on macOS. But if I 

If I run the playbook with the users setup like below. It runs but it is not idempotent and the users are "changed" every run.
```
vsftpd_users:
  - username: ftpuser
     name: FTP User
     password: "{{ 'ftpuserpassword' | password_hash('sha256') }}"
```

If I try with the following. It is idempotent.
```
vsftpd_users:
  - username: ftpuser
     name: FTP User
     password: "ftpuserpassword"
```

But I get the following warning.

`[WARNING]: The input password appears not to have been hashed. The 'password' argument must be encrypted for this module to work properly.`

And if I run it with precomputed hash as follows. It is idempotent and no warning (desired behavior).

```
vsftpd_users:
  - username: ftpuser
     name: FTP User
     password: "$6$3..."
```

Perhaps this is all working as it should?!
